AWSTemplateFormatVersion: '2010-09-09'


Description: Kubecost Masterpayer Account Template

Parameters:
  AthenaCURBucket:
    Description: The bucket where the CUR is sent from the "Setting up the CUR" step. This is in the AWS console>Billing Dashboard>Cost & usage reports>S3 Bucket for the daily report. https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations#step-1-setting-up-the-cur
    Type: String
  AthenaQueryResultsBucket:
    Description: The bucket where the Athena query output is sent. This is under Athena>Query editor>Settings. https://docs.kubecost.com/install-and-configure/install/cloud-integration/aws-cloud-integrations#step-2-setting-up-athena
    Type: String
  KubecostClusterID:
    Description: Amazon account running kubecost that requires access.
    Type: String

Resources:
  KubecostRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'KubecostRole-${KubecostClusterID}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${KubecostClusterID}:root'
            Action:
              - 'sts:AssumeRole'
  AthenaPolicy:
    Type: 'AWS::IAM::Policy'
    Properties:
      Roles:
        - !Ref KubecostRole
      PolicyName: !Sub 'kubecost-athena-access-${KubecostClusterID}'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: AthenaAccess
          Effect: Allow
          Action:
          - athena:*
          Resource:
          - "*"
        - Sid: ReadAccessToAthenaCurDataViaGlue
          Effect: Allow
          Action:
          - glue:GetDatabase*
          - glue:GetTable*
          - glue:GetPartition*
          - glue:GetUserDefinedFunction
          - glue:BatchGetPartition
          Resource:
          - arn:aws:glue:*:*:catalog
          - arn:aws:glue:*:*:database/athenacurcfn*
          - arn:aws:glue:*:*:table/athenacurcfn*/*
        - Sid: AthenaQueryBucketAccess
          Effect: Allow
          Action:
          - s3:GetBucketLocation
          - s3:ListBucket
          Resource:
          - !Sub 'arn:aws:s3:::${AthenaQueryResultsBucket}'
        - Sid: AthenaQueryResultsOutput
          Effect: Allow
          Action:
          - s3:GetBucketLocation
          - s3:GetObject
          - s3:ListBucket
          - s3:ListBucketMultipartUploads
          - s3:ListMultipartUploadParts
          - s3:AbortMultipartUpload
          - s3:CreateBucket
          - s3:PutObject
          Resource:
          - !Sub 'arn:aws:s3:::${AthenaQueryResultsBucket}/*'
        - Sid: S3AccessToBillingDataBucket
          Effect: Allow
          Action:
          - s3:GetBucketLocation
          - s3:ListBucket
          Resource:
          - !Sub 'arn:aws:s3:::${AthenaCURBucket}'
        - Sid: S3ReadAccessToAwsBillingData
          Effect: Allow
          Action:
          - s3:GetObject
          Resource:
          - !Sub 'arn:aws:s3:::${AthenaCURBucket}/*'
        - Sid: ReadAccessToAccountTags
          Effect: Allow
          Action:
          - organizations:ListAccounts
          - organizations:ListTagsForResource
          Resource:
          - "*"
